using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Shapes;
using Microsoft.Phone.Controls;

namespace PivitPan
{
    public partial class PivotPage1 : PhoneApplicationPage
    {
        public PivotPage1()
        {
            InitializeComponent();
        }

        protected override void OnNavigatedTo(System.Windows.Navigation.NavigationEventArgs e)
        {
            loadMyData();
            base.OnNavigatedTo(e);
        }

        private void loadMyData()
        {
            // add data to the pivot page sections
            tblVindaloo.Text = "Vindaloo is a hot and spicy dish from the Goa region of India " + System.Environment.NewLine + "Serves 4 people, approximately 1 hour cooking time.\n"
                                    + System.Environment.NewLine + "Ingredients: " + System.Environment.NewLine + "800g Diced Chicken breast, 1 Cup (300ml) Water with Chicken Stock, 2 Small white onions finely chopped, 2 Teaspoons Ginger Puree , 2 Teaspoons Garlic Puree , 200g Butter Ghee, 1 Teaspoon Turmeric Powder , 4 Teaspoons Mild Curry Powder , 4 Teaspoons Chilli Powder , 1 Teaspoon Garam Masala Powder , 1 Teaspoon whole Sizzling Seeds , 8 bite size pieces of cooked boiled spuds,1 Tin Chopped Tomatoes,2 Tablespoons Tomato Puree,300ml Pureed Onion,Roughly chopped fresh coriander leaves to garnish.\n"
                                    + System.Environment.NewLine + "Method: " + System.Environment.NewLine + "To make the Onion Puree, bring a small pan of water to the boil and add some chopped onions. Boil until soft, drain and puree with a hand blender or in a food processor. Freeze any extra you make for next time.Pour the oil into a large saucepan bring up to a high heat. Add the whole seeds and cook until they sizzle and crackle then add the chopped onions and reduce the heat to low. You can optionally add 1 or 2 Whole Star Anise which help bring out the sweetness of the onions and imparts a subtle aniseed flavour but remove them once the onions are cooked. Cook the onions gently and slowly until they turn a golden brown colour.Make a paste of the ginger puree, garlic puree, curry powder, Turmeric powder, Chilli powder, with a little water. Add to saucepan and stir in well and fry for a couple of minutes.Now add your 800g Diced Chicken, breast or dark meat as you prefer stir in well. Mix the Chopped Tomatoes, Tomato Puree, Onion Puree, together in a jug with the water or stock and pour into the saucepan and mixin well. Turn up the heat until the sauce begins to simmer and leave to simmer for 15-20 Minutes. Stir occasionally. Add the cooked potatoes. Finally sprinkle in the Garam masala and stir in well for the final 2 minutes of cooking. Garnish with the Roughly chopped fresh coriander leaves and serve.";

            tblMadras.Text = " Madras curry is said to originate from the south of India, and gets its name from the city known as Madras when English merchants arrived there in 1640. It has its origins in Hindu culture and thus authentic recipes are vegetarian." + System.Environment.NewLine +
            "Serves 4 people, approximately 1 hour cooking time. " + System.Environment.NewLine
                        + System.Environment.NewLine + "Ingredients: " + System.Environment.NewLine + "4 chicken breasts, one per person!, 3 tbsp vegetable oil, 2 onions ( peeled and finely chopped), 2cm block of fresh root ginger(peeled and grated), 2-3 garlic cloves (peeled and finely chopped), Sea salt and black pepper, 400g ripe tomatoes, 300ml water, 1 tsp garam masala, Coriander leaves (to Garnish), 2–4 red chillies, 2 tsp ground cumin, 1 tsp ground coriander, 1 tsp ground turmeric, 1–3 tsp (or more!) hot chilli powder , 6–8 curry leaves, Juice of half a lemon or lime.\n"
                        + System.Environment.NewLine + "Method: "
                        + System.Environment.NewLine + "Cut the chicken into strips or cubes and put aside. Heat the oil and add the onions and cook until they start to soften which will be about 5 or 6 mins. Once the onions have started to brown add the chillies, the garlic and the ginger and cook for a further 2-3 minutes. Then add the turmeric, cumin, coriander, curry leaves and chilli powder and leave to cook for a further minute or so. In that time, season the chicken you set aside earlier with the salt and pepper and add to the pan and cook stirring the pan until the chicken begins to go golden brown all over. At this stage you’ll want to add the water and the chopped tomatoes and then bring to boil. Once the pan is boiling, reduce the heat to a simmer and cover the pan stirring ever so often. Let it simmer for about 30 minutes and add more water as needed if it begins to stick or the sauce becomes too dry – remember to stir well if you do need to add water. At the end of the 30 mins, stir in the garam masala and leave uncovered for another 10 mins, again taking care not to let it dry out.";

            tblAllahMasala.Text = " Allah Masala is my own rendition of Indian cuisine. If you are offended by the name then grow up. Masala can mean someone or something that comprises a varied mixture of elements, so i feel the name is suitable aswel as funny. This curry originates from Galway, Ireland. Enjoy! " + Environment.NewLine +
            "Serves 4 people, approximately 1 hour. " + System.Environment.NewLine
                        + System.Environment.NewLine + "Ingredients: " + System.Environment.NewLine + "4 chicken breasts, one per person! A decent scoop of unclarified Ghee butter, 2 onions diced up real fine, star anise seeds, 2 red onions sliced, 1 red pepper sliced, 1 green pepper sliced, a dessert spoon of grated ginger, 3 garlic cloves (peeled and finely chopped), 1 tbsp ground peppercorns, 400g ripe tomatoes diced up, 300ml water, 1/2 tin coconut milk, 1 tsp garam masala,loads of Coriander leaves diced up, 5 red chillies, 2 tsp ground cumin, 1 tsp ground coriander, 1 tsp ground turmeric, 1–3 tsp (or more!) hot chilli powder , 6–8 curry leaves, Juice of half a lemon or lime.\n"
                        + System.Environment.NewLine + "Method: "
                        + System.Environment.NewLine + "Cut the chicken into strips or cubes and put aside. Heat the oil and add the onions and  10 star anise seeds cook until they start to soften which will be about 5 or 6 mins. Once the onions have started to brown remove the seeds add the chillies, the garlic and the ginger and cook for a further 2-3 minutes. Then add the turmeric, curry leaves, cumin, coriander, and chilli powder and leave to cook for 5 further minutes or so. In that time, season the chicken you set aside earlier with the peppercorn and add to the pan and cook stirring the pan until the chicken begins to go golden brown all over. At this stage you’ll want to add the water and the chopped tomatoes and then bring to boil. Once the pan is boiling, add the coconut milk and wait a little bit for the heat to build up again. Reduce the heat to a simmer and cover the pan stirring often. Let it simmer for about 45 minutes and add more water if needed if it begins to stick or the sauce becomes too dry – remember to stir well if you do need to add water. At the end of the 45 mins, stir in the garam masala and leave uncovered for another 10 mins, again taking care not to let it dry out. Instead of chicken, why not try a pork Allah Massala ?";

tblKorma.Text = "Korma is a creamy coconut flavoured curry, 'Korma' literally translates to 'Cooked Meat'. " + System.Environment.NewLine + "Serves 4 People, approximately 50 Minutes cooking time.\n"
                        + System.Environment.NewLine + "Ingredients: "
                        + System.Environment.NewLine + "800g Diced Chicken, breast or dark meat as you prefer, 1 Cup/300ml Water or Chicken Stock, 2 Small white onions finely chopped, 2 Teaspoons Ginger Puree, 2 Teaspoons Garlic Puree, 200g Butter Ghee, 2 Teaspoons Turmeric Powder, 4 Teaspoons Mild Curry Powder, Quarter (optional) Teaspoons Chilli Powder,2 Teaspoons Garam Masala Powder, 4 Egg Yolks Mixed with 200ml Coconut Cream, 200ml Single Cream, 100ml Natural Yogurt, Toasted Almond Slices to garnish.\n"
                        + System.Environment.NewLine + "Method:"
                        + System.Environment.NewLine + "Pour the oil into a large saucepan bring up to a medium heat. Add the onions and reduce the heat to low. You can optionally add 1 or 2 Whole Star Anise which help bring out the sweetness of the onions and imparts a subtle aniseed flavour but remove them once the onions are cooked. Cook the onions gently and slowly until they turn a golden brown colour. Make a paste of the ginger puree, garlic puree, curry powder, Turmeric powder, Chilli powder, with a little water. Add to saucepan and stir in well and fry for a couple of minutes. Now add your 800g Diced Chicken, breast or dark meat as you prefer stir in well. Add the Coconut Cream and egg mixture.Mix the Cream, Yogurt, together in a jug with the water or stock and pour into the saucepan and mix in well. Turn up the heat until the sauce begins to simmer and leave to simmer for 15-20 Minutes. Stir occasionally.Finally sprinkle in the Garam masala and stir in well for the final 2 minutes of cooking. Garnish with the Toasted Almond Slices and serve.";

            tblRoganJosh.Text = "Rogan josh was brought to Kashmir by the Mughals, whose cuisine was in turn influenced by Persian cuisine. The unrelenting summer heat of the Indian plains took the Mughals frequently to Kashmir, which has a cooler climate because of its elevation and latitude. " + System.Environment.NewLine + "Serves 4 People, approximately 50 Minutes cooking time.\n"
            + System.Environment.NewLine + "Ingredients: "
            + System.Environment.NewLine + "800g Diced Chicken, breast or dark meat as you prefer, 1 Cup/300ml Water or Chicken Stock, 2 Small white onions finely chopped, 2 Teaspoons Ginger Puree, 2 Teaspoons Garlic Puree, 200g Groundnut Oil, 1 Teaspoon Turmeric Powder, 4 Teaspoons Mild Curry Powder, Half Teaspoons Chilli Powder, 1 Teaspoon Garam Masala Powder, 1 Teaspoon whole Cumin Seeds, 1 Teaspoon whole Fennel Seeds, 8 De-seeded Tomatoes chopped in quarters, 100ml Natural Yogurt, 1 Tin Chopped Tomatoes, 2 Tablespoons Tomato Puree, 300ml Pureed Onion, Roughly Chopped Coriander leaves to garnish.\n"
            + System.Environment.NewLine + "Method:"
            + System.Environment.NewLine + "To make the Onion Puree, bring a small pan of water to the boil and add some chopped onions. Boil until soft, drain and puree with a hand blender or in a food processor. Freeze any extra you make for next time. Pour the oil into a large saucepan bring up to a high heat. Add the whole seeds and cook until they sizzle and crackle then add the chopped onions and reduce the heat to low. You can optionally add 1 or 2 Whole Star Anise which help bring out the sweetness of the onions and imparts a subtle aniseed flavour but remove them once the onions are cooked. Cook the onions gently and slowly until they turn a golden brown colour. Make a paste of the ginger puree, garlic puree, curry powder, Turmeric powder, Chilli powder, with a little water. Add to saucepan and stir in well and fry for a couple of minutes. Now add your 800g Diced Chicken, breast or dark meat as you prefer stir in well. Add the chopped tomatoes. Mix the Yogurt, Chopped Tomatoes, Tomato Puree, Onion Puree, together in a jug with the water or stock and pour into the saucepan and mix in well. Turn up the heat until the sauce begins to simmer and leave to simmer for 15-20 Minutes. Stir occasionally.Finally sprinkle in the Garam masala and stir in well for the final 2 minutes of cooking. Garnish with the Roughly Chopped Coriander leaves and serve.";


            tblLambKashmiri.Text = "Kashmiri cuisine is based on the ancient traditions of the north east Asian Kashmir area. The ancient Kashmiri epic, the Nilamat Purana, records that Kashmiris were heavy meat eaters, a habit that persists to this day. " + System.Environment.NewLine + "Serves 4 People, approximately 40 Minutes cooking time \n"
            + System.Environment.NewLine + "Ingredients: "
            + System.Environment.NewLine + "800g Diced Lean Lamb Steak, 1 Cup/300ml Water or Lamb Stock, 2 Small white onions finely chopped, 2 Teaspoons Ginger Puree, 2 Teaspoons Garlic Puree, 200g Butter Ghee, 2 Teaspoons Turmeric Powder, 4 Teaspoons Mild Curry Powder, Quarter (optional) Teaspoons Chilli Powder, 2 Teaspoons Garam Masala Powder, 4 Egg Yolks Mixed with 200ml Coconut Cream, 200ml Single Cream, 100ml Natural Yogurt, 1 Tablespoon Tomato Puree, Slices of caramelised banana. Cut the banana in 4mm thick slices, coat with sugar on both sides and heat in a dry pan until cooked and caramelised. It takes about 2-4 minutes so get ready while the curry sauce is simmering, to garnish.\n"

            + System.Environment.NewLine + "Method:"
            + System.Environment.NewLine + "Pour the oil into a large saucepan bring up to a medium heat. Add the onions and reduce the heat to low. You can optionally add 1 or 2 Whole Star Anise which help bring out the sweetness of the onions and imparts a subtle aniseed flavour but remove them once the onions are cooked. Cook the onions gently and slowly until they turn a golden brown colour. Make a paste of the ginger puree, garlic puree, curry powder, Turmeric powder, Chilli powder, with a little water. Add to saucepan and stir in well and fry for a couple of minutes. Now add your 800g Diced Lean Lamb Steak stir in well. Add the Coconut Cream and egg mixture. Mix the Cream, Yogurt, Tomato Puree, together in a jug with the water or stock and pour into the saucepan and mix in well. Turn up the heat until the sauce begins to simmer and leave to simmer for 20 Minutes. Stir occasionally.Finally sprinkle in the Garam masala and stir in well for the final 2 minutes of cooking. Garnish with the Slices of caramelised banana. Cut the banana in 4mm thick slices, coat with sugar on both sides and heat in a dry pan until cooked and caramelised. It takes about 2-4 minutes so get ready while the curry sauce is simmering. and serve.";



            tblLambPhall.Text = "Phall (sometimes spelled fall, faal, fahl, phaal, phal or paal) is a British Asian Indian curry dish, which originated in Indian restaurants in Birmingham, UK." + System.Environment.NewLine + "Serves 4 People, approximately 45 Minutes cooking time\n"
            + System.Environment.NewLine + "Ingredients: "
            + System.Environment.NewLine + "800g Diced Lean Lamb Steak, 1 Cup/300ml Water or Lamb Stock, 2 Small white onions finely chopped, 2 Teaspoons Ginger Puree, 2 Teaspoons Garlic Puree, 200g Butter Ghee, 1 Teaspoon Turmeric Powder, 4 Teaspoons Mild Curry Powder, 6 Teaspoons Chilli Powder, 1 Teaspoon Garam Masala Powder, 1 Teaspoon whole Mustard Seeds, 1 Teaspoon whole Fenugreek Seeds, 1 Tin Chopped Tomatoes, 2 Tablespoons Tomato Puree, Pureed Onion, Roughly chopped fresh coriander leaves to garnish.\n"

            + System.Environment.NewLine + "Method:"
            + System.Environment.NewLine + "To make the Onion Puree, bring a small pan of water to the boil and add some chopped onions. Boil until soft, drain and puree with a hand blender or in a food processor. Freeze any extra you make for next time. Pour the oil into a large saucepan bring up to a high heat. Add the whole seeds and cook until they sizzle and crackle then add the chopped onions and reduce the heat to low. You can optionally add 1 or 2 Whole Star Anise which help bring out the sweetness of the onions and imparts a subtle aniseed flavour but remove them once the onions are cooked. Cook the onions gently and slowly until they turn a golden brown colour. Make a paste of the ginger puree, garlic puree, curry powder, Turmeric powder, Chilli powder, with a little water. Add to saucepan and stir in well and fry for a couple of minutes. Now add your 800g Diced Lean Lamb Steak stir in well. Mix the Chopped Tomatoes, Tomato Puree, Onion Puree, together in a jug with the water or stock and pour into the saucepan and mix in well. Turn up the heat until the sauce begins to simmer and leave to simmer for 20 Minutes. Stir occasionally. Finally sprinkle in the Garam masala and stir in well for the final 2 minutes of cooking. Garnish with the Roughly chopped fresh coriander leaves and serve.";

            tblLambTikkaBalti.Text = "A Balti (Balti: བལི་, Urdu: بلتی‎) is a type of curry served in a thin, pressed steel wok-like balti bowl'" + System.Environment.NewLine + "Serves 4 People, approximately 65 Minutes cooking time\n"
            + System.Environment.NewLine + "Ingredients: "
            + System.Environment.NewLine + "800g Cooked Lamb Tikka, 1 Cup/300ml Water or Lamb Stock, 2 Small white onions finely chopped, 2 Teaspoons Ginger Puree, 2 Teaspoons Garlic Puree, 200g Butter Ghee, 2 Teaspoons Turmeric Powder, 4 Teaspoons Mild Curry Powder, 1 Teaspoon Chilli Powder, 3 Teaspoons Garam Masala Powder, 1 Teaspoon whole Mustard Seeds, 3 Carrots boiled and pureed, 100ml Single Cream, 100ml Natural Yogurt, 4 Tablespoons Tomato Puree, 200ml Pureed Onion, Roughly chopped fresh coriander leaves to garnish.\n"

            + System.Environment.NewLine + "Method:"
            + System.Environment.NewLine + "To make the Onion Puree, bring a small pan of water to the boil and add some chopped onions. Boil until soft, drain and puree with a hand blender or in a food processor. Freeze any extra you make for next time. Pour the oil into a large saucepan bring up to a high heat. Add the whole seeds and cook until they sizzle and crackle then add the chopped onions and reduce the heat to low. You can optionally add 1 or 2 Whole Star Anise which help bring out the sweetness of the onions and imparts a subtle aniseed flavour but remove them once the onions are cooked. Cook the onions gently and slowly until they turn a golden brown colour. Make a paste of the ginger puree, garlic puree, curry powder, Turmeric powder, Chilli powder, with a little water. Add to saucepan and stir in well and fry for a couple of minutes. Now add your 800g Cooked Lamb Tikka stir in well. Add the pureed carrot. Mix the Cream, Yogurt, Tomato Puree, Onion Puree, together in a jug with the water or stock and pour into the saucepan and mix in well. Turn up the heat until the sauce begins to simmer and leave to simmer for 10 Minutes. Stir occasionally. Finally sprinkle in the Garam masala and stir in well for the final 2 minutes of cooking. Garnish with the Roughly chopped fresh coriander leaves and serve.";

            tblBeefKorai.Text = "The Korai are are a Baloch tribe settled in the Balochistan province of Iran, Punjab provinces of Pakistan, and the Indian states of Uttar Pradesh, Rajasthan, Gujarat, Maharastra, Haryana, and Punjab." + System.Environment.NewLine + "Serves 4 People, approximately 50 Minutes cooking time.\n"
            + System.Environment.NewLine + "Ingredients: "
            + System.Environment.NewLine + "800g Diced Lean Beef Steak, 1 Cup/300ml Water or Beef Stock, 2 Small white onions finely chopped, 2 Teaspoons Ginger Puree, 2 Teaspoons Garlic Puree, 200g Butter Ghee, 1 Teaspoon Turmeric Powder, 4 Teaspoons Mild Curry Powder, 1 Teaspoon Chilli Powder, 3 Teaspoons Garam Masala Powder, 1 Teaspoon whole Panch Puren Seeds, 2 Red Peppers Chopped in large chunks, Half a Tin of Chopped Tomatoes, 1 Tablespoon Tomato Puree, 50ml Pureed Onion, Roughly chopped fresh coriander leaves to garnish\n"
            + System.Environment.NewLine + "Method:"
            + System.Environment.NewLine + "To make the Onion Puree, bring a small pan of water to the boil and add some chopped onions. Boil until soft, drain and puree with a hand blender or in a food processor. Freeze any extra you make for next time. Pour the oil into a large saucepan bring up to a high heat. Add the whole seeds and cook until they sizzle and crackle then add the chopped onions and reduce the heat to low. You can optionally add 1 or 2 Whole Star Anise which help bring out the sweetness of the onions and imparts a subtle aniseed flavour but remove them once the onions are cooked. Cook the onions gently and slowly until they turn a golden brown colour. Make a paste of the ginger puree, garlic puree, curry powder, Turmeric powder, Chilli powder, with a little water. Add to saucepan and stir in well and fry for a couple of minutes.Now add your 800g Diced Lean Beef Steak stir in well.Add the chopped peppers. Mix the Chopped Tomatoes, Tomato Puree, Onion Puree, together in a jug with the water or stock and pour into the saucepan and mix in well. Turn up the heat until the sauce begins to simmer and leave to simmer for 20 Minutes. Stir occasionally.Finally sprinkle in the Garam masala and stir in well for the final 2 minutes of cooking. Garnish with the Roughly chopped fresh coriander leaves and serve.";

              /*  tblBeefTikkaMassalla.Text = "Rogan josh was brought to Kashmir by the Mughals, whose cuisine was in turn influenced by Persian cuisine. The unrelenting summer heat of the Indian plains took the Mughals frequently to Kashmir, which has a cooler climate because of its elevation and latitude. " + System.Environment.NewLine + "Serves 4 People, approximately 50 Minutes cooking time "
                + System.Environment.NewLine + "Ingredients: "
                + System.Environment.NewLine + "800g Diced Chicken, breast or dark meat as you prefer, 1 Cup/300ml Water or Chicken Stock, 2 Small white onions finely chopped, 2 Teaspoons Ginger Puree, 2 Teaspoons Garlic Puree, 200g Groundnut Oil, 1 Teaspoon Turmeric Powder, 4 Teaspoons Mild Curry Powder, Half Teaspoons Chilli Powder, 1 Teaspoon Garam Masala Powder, 1 Teaspoon whole Cumin Seeds, 1 Teaspoon whole Fennel Seeds, 8 De-seeded Tomatoes chopped in quarters, 100ml Natural Yogurt, 1 Tin Chopped Tomatoes, 2 Tablespoons Tomato Puree, 300ml Pureed Onion, Roughly Chopped Coriander leaves to garnish"
                + System.Environment.NewLine + "Method:"
                + System.Environment.NewLine + "To make the Onion Puree, bring a small pan of water to the boil and add some chopped onions. Boil until soft, drain and puree with a hand blender or in a food processor. Freeze any extra you make for next time. Pour the oil into a large saucepan bring up to a high heat. Add the whole seeds and cook until they sizzle and crackle then add the chopped onions and reduce the heat to low. You can optionally add 1 or 2 Whole Star Anise which help bring out the sweetness of the onions and imparts a subtle aniseed flavour but remove them once the onions are cooked. Cook the onions gently and slowly until they turn a golden brown colour. Make a paste of the ginger puree, garlic puree, curry powder, Turmeric powder, Chilli powder, with a little water. Add to saucepan and stir in well and fry for a couple of minutes. Now add your 800g Diced Chicken, breast or dark meat as you prefer stir in well. Add the chopped tomatoes. Mix the Yogurt, Chopped Tomatoes, Tomato Puree, Onion Puree, together in a jug with the water or stock and pour into the saucepan and mix in well. Turn up the heat until the sauce begins to simmer and leave to simmer for 15-20 Minutes. Stir occasionally.Finally sprinkle in the Garam masala and stir in well for the final 2 minutes of cooking. Garnish with the Roughly Chopped Coriander leaves and serve.";

                   */


        }
    }
}